#!name=Fileball
#!desc=Fileball会员
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/fileball.png

[rewrite_local]

^https?:\/\/api\.revenuecat\.com\/v1\/(receipts|subscribers\/\$RCAnonymousID%3A\w{32})$ url script-response-body https://raw.githubusercontent.com/89996462/Quantumult-X/main/ycdz/fileball.js

^https:\/\/app-measurement\.com\/config\/app\/1?(.*?)*$ url reject

projects = type=http-response,pattern=^https://firebaseremoteconfig.googleapis.com/v1/projects/filebox-ac299/.*,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/Alex0510/Eric/master/surge/Script/projects.js

Fileball会员=type=http-response,pattern=^https?:\/\/api\.revenuecat\.com\/v1\/(receipts|subscribers\/\$RCAnonymousID%3A\w{32})$,requires-body=1,script-path=https://raw.githubusercontent.com/89996462/Quantumult-X/main/ycdz/fileball.js


[MITM] 

hostname = %APPEND% api.revenuecat.com, app-measurement.com,*.googleapis.com

